version: '3.3'

services:

  master:
    environment:
      TZ: Europe/Oslo
    image: fintlabs.azurecr.io/jenkins-master:12
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /jenkins:/var/jenkins_home
    restart: unless-stopped

  slave:
    environment:
      TZ: Europe/Oslo
    image: fintlabs.azurecr.io/jenkins-slave:12
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      - master
    restart: unless-stopped
